### PR TITLE
Update index.js setInterval() → enableRateLimit: true

### PR DESCRIPTION
**Pull request by kroitor**
Switched `setInterval() → enableRateLimit: true` to use the built-in rate-limiting REST long poller.

### CODE REVIEW

**Comment by luchenwei9266** [comment]
Thanks for your guidance！！
But I have a problem, when my exchange is binance, the command line will be an error：

```
 (node: 7372) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: binance GET https://www.binance.com / api / v1 / ticker / 24hr? symbol = NEOBTC request timed ou
t
(node: 7372) [DEP0018] DeprecationWarning: Unhandled lead rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a n
on-zero exit code
```

if is exchange  is bittrex or other，the code is no problem，so why???

Because my IP is China IP???

**Comment by kroitor** [comment]
@luchenwei9266 let's check if they are restricting China, try this:

```JavaScript
let exchange = new ccxt.binance({
     enableRateLimit: true, // built-in rate limiting REST long poller
     proxy: 'https://cors-anywhere.herokuapp.com/', //  ← add this line, last slash is critical
  })
```

or this:

```JavaScript
let exchange = new ccxt.binance({
     enableRateLimit: true, // built-in rate limiting REST long poller
     proxy: 'https://crossorigin.me/', //  ← add this line, last slash is critical
  })
```

Does any of the above snippets work for you if you edit the exchange instantiation in index.js ?

**Comment by luchenwei9266** [comment]
@kroitor Thank you for your answer, but these two ways I have just tried it again, still not, or there will be that error

**Comment by kroitor** [comment]
I just tried it from Moscow and it works without proxy and with proxy. I guess it also works for most of our users. So this is likely an issue with your location/host/IP, that kind.

**Comment by kroitor** [comment]
@luchenwei9266 Can you try running it from a remote server somewhere outside China for a test?

**Comment by luchenwei9266** [comment]
@kroitor Because China IP can not be traded in Binance, I think this error may be caused by this reason, so I try to use a foreign server, or do not use Binance Exchange.
No matter how, thank you very much for your answer！！！

**Comment by kroitor** [comment]
@luchenwei9266 I contacted Binance lead dev, and his reply was:

screen shot 2017-10-23 at 11 03 18

**Comment by kroitor** [comment]
https://support.binance.com/hc/en-us/articles/115001444731-Binance-Update-2017-09-06

**Comment by luchenwei9266** [comment]
okay, thank you. However, I found another possibility, because I usually use the VPN at work, so there may be Shadowsocks lead to this error, when I have time to let me be a test, and then I tell you the results

**Pull request merged**
